//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.24 at 01:15:39 PM EST 
//


package com.bbn.marti.excheck.checklist;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for checklistStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * {@code
 * &lt;complexType name="checklistStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="statusCount" type="{}statusCount" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="checklistUid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="checklistName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * } 
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "checklistStatus")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "checklistStatus", propOrder = {
    "statusCount"
})
public class ChecklistStatus {

    @XmlElement(required = true)
    protected List<StatusCount> statusCount;
    @XmlAttribute(name = "checklistUid")
    protected String checklistUid;
    @XmlAttribute(name = "checklistName")
    protected String checklistName;

    /**
     * Gets the value of the statusCount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statusCount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatusCount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatusCount }
     * 
     * 
     */
    public List<StatusCount> getStatusCount() {
        if (statusCount == null) {
            statusCount = new ArrayList<StatusCount>();
        }
        return this.statusCount;
    }

    /**
     * Gets the value of the checklistUid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChecklistUid() {
        return checklistUid;
    }

    /**
     * Sets the value of the checklistUid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChecklistUid(String value) {
        this.checklistUid = value;
    }

    /**
     * Gets the value of the checklistName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChecklistName() {
        return checklistName;
    }

    /**
     * Sets the value of the checklistName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChecklistName(String value) {
        this.checklistName = value;
    }

}
