//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.20 at 10:20:34 PM EST 
//


package com.bbn.marti.excheck.checklist;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bbn.marti.excheck.checklist package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bbn.marti.excheck.checklist
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ChecklistStatus }
     * 
     */
    public ChecklistStatus createChecklistStatus() {
        return new ChecklistStatus();
    }

    /**
     * Create an instance of {@link Missions }
     * 
     */
    public Missions createMissions() {
        return new Missions();
    }

    /**
     * Create an instance of {@link ChecklistDetails }
     * 
     */
    public ChecklistDetails createChecklistDetails() {
        return new ChecklistDetails();
    }

    /**
     * Create an instance of {@link ChecklistColumn }
     * 
     */
    public ChecklistColumn createChecklistColumn() {
        return new ChecklistColumn();
    }

    /**
     * Create an instance of {@link Templates }
     * 
     */
    public Templates createTemplates() {
        return new Templates();
    }

    /**
     * Create an instance of {@link ChecklistTasks }
     * 
     */
    public ChecklistTasks createChecklistTasks() {
        return new ChecklistTasks();
    }

    /**
     * Create an instance of {@link StatusCount }
     * 
     */
    public StatusCount createStatusCount() {
        return new StatusCount();
    }

    /**
     * Create an instance of {@link Checklist }
     * 
     */
    public Checklist createChecklist() {
        return new Checklist();
    }

    /**
     * Create an instance of {@link ChecklistColumns }
     * 
     */
    public ChecklistColumns createChecklistColumns() {
        return new ChecklistColumns();
    }

    /**
     * Create an instance of {@link ChecklistTask }
     * 
     */
    public ChecklistTask createChecklistTask() {
        return new ChecklistTask();
    }

}
