ARG TAKSERVER_IMAGE_REPO=docker-devtest-local.artifacts.tak.gov/takserver-cluster/takserver-base
ARG TAKSERVER_IMAGE_TAG=core-base
FROM ${TAKSERVER_IMAGE_REPO}:${TAKSERVER_IMAGE_TAG}
CMD ["sh", "takserver-api-cluster.sh"]