FROM eclipse-temurin:17-jammy
RUN apt-get update && \
    apt-get install -y \
        python3 \
        python3-dev \
        python3-pip \
        python3-setuptools \
        groff \
        less \
    && pip3 install --upgrade awscli \
    && pip3 install --upgrade boto3 \
    && apt-get clean
COPY takserver-schemamanager/* ./
COPY CoreConfig.xml /opt/tak/CoreConfig.xml

# start postgres, and configure TAK server database
ENTRYPOINT ["python3", "pollRDS.py"]


