FROM openjdk:11-jdk-bullseye
COPY takserver-core/takserver-core*.war takserver.war
COPY takserver-usermanager/UserManager.jar .
COPY CoreConfig.xml .
COPY takserver-schemamanager/SchemaManager.jar .
COPY takserver-core/logging-restrictsize.xml .
COPY takserver-core/takserver.sh .
COPY takserver-core/API/takserver-api-cluster.sh .
COPY takserver-core/messaging/takserver-messaging-cluster.sh .
COPY takserver-core/UserAuthenticationFile.xml .
COPY takserver-core/setenv-cluster.sh ./setenv.sh
COPY takserver-core/enable_admin.sh .
COPY takserver-core/messaging-readiness.sh .
COPY takserver-core/api-readiness.sh .
COPY takserver-schemamanager/db-connection-configuration.sh .
RUN chmod +x takserver-api-cluster.sh && \
	chmod +x takserver-messaging-cluster.sh && \
	chmod +x messaging-readiness.sh && \
	chmod +x api-readiness.sh && \
	chmod +x setenv.sh && \
	chmod +x db-connection-configuration.sh && \
	apt-get update && \
	apt-get install -y emacs-nox net-tools netcat 
RUN chmod +x takserver.sh
RUN ./db-connection-configuration.sh
CMD ["jshell"]
