FROM postgres:15.1
# this is slow - updates all packages
RUN apt-get update && apt install -y postgresql-15-postgis-3

# install openjdk 11
RUN echo 'deb http://ftp.debian.org/debian stretch-backports main' > /etc/apt/sources.list.d/pgdg.list && \
	apt update && \
	apt-get -y -t stretch-backports install openjdk-11-jdk
