#!/bin/bash
### BEGIN INIT INFO
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: takserver init script
### END INIT INFO
#
# /etc/rc.d/init.d/takserver
#
# (c)2015-2018 Raytheon BBN Technologies. Licensed to US Government with unlimited rights.
#
# The Team Awareness Kit (TAK) server is a network server supporting the
# family of TAK situation-awareness applications, such as the Android
# Team Awareness Kit (ATAK) and Windows Team Awareness Kit (WinTAK). TAK
# server provides brokering, filtering, and archiving of Cursor-on-Target
# (CoT) information and provides interconnectivity to client devices on
# non-multicast networks.
#
# This script starts the takserver-messaging, takserver-api and takserver-plugins services


# chkconfig: 345 20 40
# description: Team Awareness Kit (TAK) information brokering and management service.

# Source function library
if [ -f /etc/rc.d/init.d/functions ]; then
    . /etc/rc.d/init.d/functions
fi

SERVICE="TAK server"
TAK_HOME=/opt/tak

case "$1" in
     start)
        echo -n "Starting $SERVICE: "
		    service takserver-messaging start
		    service takserver-api start
		    service takserver-plugins start
		    service takserver-retention start
        touch "/var/lock/subsys/$SERVICE"
    ;;
    stop)
        echo -n "Shutting down $SERVICE: "
    		service takserver-messaging stop
		    service takserver-api stop
		    service takserver-plugins stop
		    service takserver-retention stop
	      rm -f "/var/lock/subsys/$SERVICE"
	      echo "done."
    ;;
    status)
        RETVAL=0
        TAK_PID=`pgrep -f "spring.profiles.active=messaging"`
        if [ $? -eq 0 ] ; then
            echo "takserver-messaging is running with pid ${TAK_PID}"
        else
            echo "takserver-messaging is not running."
            RETVAL=1
        fi

        TAK_PID=`pgrep -f "spring.profiles.active=api"`
        if [ $? -eq 0 ] ; then
            echo "takserver-api is running with pid ${TAK_PID}"
        else
            echo "takserver-api is not running."
            RETVAL=1
        fi

        TAK_PID=`pgrep -f "takserver-pm.jar"`
        if [ $? -eq 0 ] ; then
            echo "takserver-plugins is running with pid ${TAK_PID}"
        else
            echo "takserver-plugins is not running."
            RETVAL=1
        fi

        TAK_PID=`pgrep -f "takserver-retention.jar"`
        if [ $? -eq 0 ] ; then
            echo "takserver-retention is running with pid ${TAK_PID}"
        else
            echo "takserver-retention is not running."
            RETVAL=1
        fi

        exit $RETVAL
    ;;
    restart)
          $0 stop;
          $0 start;
    ;;
    reload)
          $0 stop;
          $0 start;
    ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
       exit 1
    ;;
esac

exit 0
