//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.07.26 at 10:49:00 AM EDT
//


package com.bbn.marti.util.missionpackage;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.locationtech.jts.geom.Point;


/**
 * <p>Java class for ContentType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * {@code
 * &lt;complexType name="ContentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Parameter" type="{}ParameterType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="zipEntry" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ignore" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * }
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentType", propOrder = {
    "parameter"
})
public class ContentType {

    @XmlElement(name = "Parameter")
    protected ParameterType parameter;
    @XmlAttribute(name = "zipEntry")
    protected String zipEntry;
    @XmlAttribute(name = "ignore")
    protected Boolean ignore;
    @XmlAttribute(name = "keywords")
    protected String keywords;
    @XmlAttribute(name = "mimeType")
    protected String mimeType;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "submitter")
    protected String submitter;
    @XmlAttribute(name = "uid")
    protected String uid;
    @XmlAttribute(name = "creatorUid")
    protected String creatorUid;
    @XmlAttribute(name = "size")
    protected Long size;
    @XmlAttribute(name = "tool")
    protected String tool;
    @XmlAttribute(name = "latitude")
    protected Double latitude;
    @XmlAttribute(name = "longitude")
    protected Double longitude;
    @XmlAttribute(name = "altitude")
    protected Double altitude;
    @XmlAttribute(name = "submissionTime")
    protected String submissionTime;
    @XmlAttribute(name = "filename")
    protected String filename;

    /**
     * Gets the value of the parameter property.
     *
     * @return
     *     possible object is
     *     {@link ParameterType }
     *
     */
    public ParameterType getParameter() {
        return parameter;
    }

    /**
     * Sets the value of the parameter property.
     *
     * @param value
     *     allowed object is
     *     {@link ParameterType }
     *
     */
    public void setParameter(ParameterType value) {
        this.parameter = value;
    }

    /**
     * Gets the value of the zipEntry property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getZipEntry() {
        return zipEntry;
    }

    /**
     * Sets the value of the zipEntry property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setkeywords(String value) {
        this.keywords = value;
    }

    /**
     * Gets the value of the zipEntry property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the zipEntry property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setZipEntry(String value) {
        this.zipEntry = value;
    }

    /**
     * Gets the value of the ignore property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isIgnore() {
        return ignore;
    }

    /**
     * Sets the value of the ignore property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setIgnore(Boolean value) {
        this.ignore = value;
    }

	public String getMimeType() {
		return mimeType;
	}

	public void setMimeType(String mimeType) {
		this.mimeType = mimeType;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSubmitter() {
		return submitter;
	}

	public void setSubmitter(String submitter) {
		this.submitter = submitter;
	}

	public String getUid() {
		return uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public String getCreatorUid() {
		return creatorUid;
	}

	public void setCreatorUid(String creatorUid) {
		this.creatorUid = creatorUid;
	}

	public Long getSize() {
		return size;
	}

	public void setSize(Long size) {
		this.size = size;
	}

	public String getSubmissionTime() {
		return submissionTime;
	}

	public void setSubmissionTime(String submissionTime) {
		this.submissionTime = submissionTime;
	}

	public String getTool() {
		return tool;
	}

	public void setTool(String tool) {
		this.tool = tool;
	}

	public String getFilename() {
		return filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}


	public Double getLatitude() {
		return latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getLongitude() {
		return longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getAltitude() {
		return altitude;
	}

	public void setAltitude(Double altitude) {
		this.altitude = altitude;
	}

	public Boolean getIgnore() {
		return ignore;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}



}
