package com.bbn.marti.service;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import java.io.StringReader;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.Unmarshaller;

import org.junit.Before;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import ch.qos.logback.classic.Level;

import com.bbn.marti.model.kml.Icon;
import com.bbn.marti.model.kml.Iconset;

/**
 * Unit tests for deserialization of Iconset and Icon objects
 * 
 * 
 */

public class IconsetIconTest {

    String iconsetXml = "<iconset name=\"Default\" uid=\"34ae1613-9645-4222-a9d2-e5f243dea2865\" defaultFriendly=\"salute.png\" defaultHostile=\"robber.png\" defaultNeutral=\"soldier5.png\" defaultUnknown=\"suspect.png\" skipResize=\"true\" version=\"1\">\n" + 
            "   <icon name=\"antelope.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"bat.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"bear.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"bear2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"beehive.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"bird.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"bull.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"bull2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"butterfly.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"camel.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"camel2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"caribou.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"chicken.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"cow.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"cow2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"cow3.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"cow4.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"cow5.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"croc.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"deer.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"deer2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"deer3.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"dolphin.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"donkey.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"donkey2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"donkey3.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"duck.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"duck2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"duck3.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"eagle.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"elephant.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"elephant2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"fly.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"fox.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"geese.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"giraffe.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"goat.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"goose.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"goose2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"gorilla.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"grizzly.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"hen.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"honeybadger.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"horse.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"kangaroo.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"lion.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"lioness.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"lizard.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"llama.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"mosquito.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"owl.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"panther.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"pawprint.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"pig.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"pig2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"pig3.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"pigeon.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"rabbit.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"rabbit1.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"rhino.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"rhino2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"rooster.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"scorpion.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"sheep.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"sheep1.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"spider.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"squirell.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"squirell1.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"starfish.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"swallow.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"swan.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"tick.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"turkey.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"turtle.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"turtle2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"whale.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"apartments.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"apartments2.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"bank.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"brick.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"buddhistTemple.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"buildings.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"buildings2.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"buildings3.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"buildings4.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"buildings5.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"capitol.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"castle.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"castle1.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"cathedral.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"cathedral2.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"chapel.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"church1.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"church2.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"city.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"cityline.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"condo.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"controltower.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"crane.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"embassy.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"factory.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"factory2.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"factory3.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"farm.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"farm2.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"ferriswheel.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"firehouse.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"firehydrant.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"fountain.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"garage.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"government.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"highrises.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"hospital.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"hotel.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"house.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"house2.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"house3.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"house4.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"house5.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"house6.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"house7.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"lighthouse.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"mission.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"monument.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"Mosque.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"museum.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"ngo.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"office.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"Orthodox.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"parkingmeter.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"pyramid.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"pyramid2.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"rowhouse.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"shops.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"skyscraper.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"tentlarge.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"tower.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"tower2.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"townhouse.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"un.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"university.png\" type2525b=\"a-u-G-I\"/>\n" + 
            "   <icon name=\"Abkhazia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Afghanistan.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Aland.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Albania.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Algeria.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"American-Samoa.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Andorra.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Angola.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Anguilla.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Antarctica.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Antigua-and-Barbuda.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Argentina.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Armenia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Aruba.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Australia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Austria.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Azerbaijan.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Bahamas.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Bahrain.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Bangladesh.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Barbados.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Basque-Country.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Belarus.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Belgium.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Belize.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Benin.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Bermuda.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Bhutan.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Bolivia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Bosnia-and-Herzegovina.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Botswana.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Brazil.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"British-Antarctic-Territory.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"British-Virgin-Islands.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Brunei.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Bulgaria.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Burkina-Faso.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Burundi.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Cambodia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Cameroon.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Canada.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Canary-Islands.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Cape-Verde.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Cayman-Islands.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Central-African-Republic.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Chad.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Chile.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"China.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Christmas-Island.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Cocos-Keeling-Islands.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Colombia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Commonwealth.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Comoros.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Cook-Islands.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Costa-Rica.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Cote-dIvoire.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Croatia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Cuba.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Curacao.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Cyprus.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Czech-Republic.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Democratic-Republic-of-the-Congo.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Denmark.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Djibouti.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Dominica.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Dominican-Republic.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"East-Timor.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Ecuador.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Egypt.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"El-Salvador.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"England.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Equatorial-Guinea.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Eritrea.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Estonia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Ethiopia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"European-Union.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Falkland-Islands.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Faroes.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Fiji.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Finland.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"France.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"French-Polynesia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"French-Southern-Territories.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Gabon.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Gambia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Georgia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Germany.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Ghana.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Gibraltar.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"GoSquared.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Greece.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Greenland.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Grenada.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Guam.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Guatemala.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Guernsey.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Guinea-Bissau.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Guinea.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Guyana.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Haiti.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Honduras.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Hong-Kong.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Hungary.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Iceland.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"India.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Indonesia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Iran.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Iraq.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Ireland.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Isle-of-Man.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Israel.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Italy.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Jamaica.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Japan.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Jersey.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Jordan.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Kazakhstan.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Kenya.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Kiribati.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Kosovo.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Kuwait.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Kyrgyzstan.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Laos.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Latvia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Lebanon.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Lesotho.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Liberia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Libya.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Liechtenstein.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Lithuania.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Luxembourg.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Macau.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Macedonia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Madagascar.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Malawi.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Malaysia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Maldives.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Mali.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Malta.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Mars.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Marshall-Islands.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Martinique.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Mauritania.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Mauritius.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Mayotte.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Mexico.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Micronesia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Moldova.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Monaco.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Mongolia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Montenegro.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Montserrat.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Morocco.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Mozambique.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Myanmar.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Nagorno-Karabakh.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Namibia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"NATO.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Nauru.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Nepal.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Netherlands-Antilles.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Netherlands.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"New-Caledonia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"New-Zealand.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Nicaragua.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Niger.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Nigeria.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Niue.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Norfolk-Island.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"North-Korea.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Northern-Cyprus.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Northern-Mariana-Islands.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Norway.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Olympics.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Oman.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Pakistan.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Palau.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Palestine.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Panama.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Papua-New-Guinea.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Paraguay.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Peru.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Philippines.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Pitcairn-Islands.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Poland.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Portugal.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Puerto-Rico.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Qatar.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Red-Cross.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Republic-of-the-Congo.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Romania.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Russia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Rwanda.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Saint-Barthelemy.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Saint-Helena.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Saint-Kitts-and-Nevis.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Saint-Lucia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Saint-Martin.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Saint-Vincent-and-the-Grenadines.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Samoa.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"San-Marino.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Sao-Tome-and-Principe.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Saudi-Arabia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Scotland.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Senegal.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Serbia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Seychelles.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Sierra-Leone.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Singapore.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Slovakia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Slovenia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Solomon-Islands.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Somalia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Somaliland.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"South-Africa.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"South-Georgia-and-the-South-Sandwich-Islands.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"South-Korea.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"South-Ossetia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"South-Sudan.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Spain.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Sri-Lanka.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Sudan.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Suriname.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Swaziland.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Sweden.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Switzerland.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Syria.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Taiwan.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Tajikistan.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Tanzania.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Thailand.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Togo.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Tokelau.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Tonga.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Trinidad-and-Tobago.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Tunisia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Turkey.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Turkmenistan.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Turks-and-Caicos-Islands.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Tuvalu.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Uganda.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Ukraine.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"United-Arab-Emirates.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"United-Kingdom.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"United-Nations.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"United-States.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Unknown.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Uruguay.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"US-Virgin-Islands.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Uzbekistan.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Vanuatu.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Vatican-City.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Venezuela.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Vietnam.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Wales.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Wallis-And-Futuna.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Western-Sahara.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Yemen.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Zambia.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Zimbabwe.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"backpack.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"boot.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"cabin.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"camp.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"camp2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"camp3.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"campsite.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"climbing.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"compass.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"hatchet.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"hatchets.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"hiker.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"hiking.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"map.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"mountain.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"mountain2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"mountain3.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"potablewater.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"star.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"summit.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"tent.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"tent2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"tent3.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"tent4.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"water.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"wood.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"antlers.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"archer.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"archery.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"arrow.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"arrow2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"arrow3.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"birddog.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"boar.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"bow.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"bow2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"buck.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"buck2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"buck3.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"cat.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"coyote.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"crosshair.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"crosshair1.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"deerlarge.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"deer_crosshair.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"doe.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"doe2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"elk.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"elk2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"fish.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"fishing.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"fishing2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"huntingblind.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"largemouth.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"moose.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"moose2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"pheasant.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"quail.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"rabbitcrosshair.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"reticle.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"reticle2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"rifle2.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"scope.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"scope2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"scope3.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"shotgun2.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"shotgun3.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"smallmouth.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"spear.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"speargun.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"spotting.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"target.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"target2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"target3.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"target4.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"tom.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"tracks.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"trap.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"treestand.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"treestand2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"A10.png\" type2525b=\"a-u-A-M-F\"/>\n" + 
            "   <icon name=\"aircraftcarrier.png\" type2525b=\"a-u-S-C-L-C-V\"/>\n" + 
            "   <icon name=\"airdrop.png\" type2525b=\"a-u-A\"/>\n" + 
            "   <icon name=\"airman.png\" type2525b=\"a-u-A\"/>\n" + 
            "   <icon name=\"AK47.png\" type2525b=\"a-u-G-E-W-R\"/>\n" + 
            "   <icon name=\"apache.png\" type2525b=\"a-u-A-M-H\"/>\n" + 
            "   <icon name=\"artillary.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"assaultship.png\" type2525b=\"a-u-S-C-A-L-A\"/>\n" + 
            "   <icon name=\"AV8B.png\" type2525b=\"a-u-A-M-F-A\"/>\n" + 
            "   <icon name=\"B2.png\" type2525b=\"a-u-A-M-F-B\"/>\n" + 
            "   <icon name=\"B52.png\" type2525b=\"a-u-A-M-F-A\"/>\n" + 
            "   <icon name=\"blackhawk.png\" type2525b=\"a-u-A-M-H\"/>\n" + 
            "   <icon name=\"blackhawk1.png\" type2525b=\"a-u-A-M-H\"/>\n" + 
            "   <icon name=\"blackhawk2.png\" type2525b=\"a-u-A-M-H\"/>\n" + 
            "   <icon name=\"bomb.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"bomber.png\" type2525b=\"a-u-A-M-F-B\"/>\n" + 
            "   <icon name=\"bombing.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"bullet.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"C-17.png\" type2525b=\"a-u-A-M-F\"/>\n" + 
            "   <icon name=\"canon.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"canon2.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"canon3.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"chinook.png\" type2525b=\"a-u-A-M-H-C\"/>\n" + 
            "   <icon name=\"Chinook2.png\" type2525b=\"a-u-A-M-H-C\"/>\n" + 
            "   <icon name=\"commander.png\" type2525b=\"a-u-G-U-U-S-O\"/>\n" + 
            "   <icon name=\"convoy.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"cruiser.png\" type2525b=\"a-u-S-C-L-C-C\"/>\n" + 
            "   <icon name=\"CV-22.png\" type2525b=\"a-u-A-M-H\"/>\n" + 
            "   <icon name=\"CV_22.png\" type2525b=\"a-u-A-M-H\"/>\n" + 
            "   <icon name=\"destroyer.png\" type2525b=\"a-u-S-C-L-D-D\"/>\n" + 
            "   <icon name=\"DogTags.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"DroneTarget.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"EA-6B.png\" type2525b=\"a-u-A-M-F\"/>\n" + 
            "   <icon name=\"Explosion.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"F111A.png\" type2525b=\"a-u-A-M-F-F\"/>\n" + 
            "   <icon name=\"F117.png\" type2525b=\"a-u-A-M-F-F\"/>\n" + 
            "   <icon name=\"F15.png\" type2525b=\"a-u-A-M-F-F\"/>\n" + 
            "   <icon name=\"F16.png\" type2525b=\"a-u-A-M-F-F\"/>\n" + 
            "   <icon name=\"F18.png\" type2525b=\"a-u-A-M-F-F\"/>\n" + 
            "   <icon name=\"F22.png\" type2525b=\"a-u-A-M-F-F\"/>\n" + 
            "   <icon name=\"F35.png\" type2525b=\"a-u-A-M-F-F\"/>\n" + 
            "   <icon name=\"fastrope.png\" type2525b=\"a-u-A-M-H\"/>\n" + 
            "   <icon name=\"fastrope2.png\" type2525b=\"a-u-A-M-H\"/>\n" + 
            "   <icon name=\"fortress.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Glock.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"Grenade.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"GunTruck.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"helmet.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Humvee.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"ISR.png\" type2525b=\"a-u-A-M-F\"/>\n" + 
            "   <icon name=\"ISR2.png\" type2525b=\"a-u-A-M-F\"/>\n" + 
            "   <icon name=\"jeep.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"jeep2.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"jeep3.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"jeep4.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"K9.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"knife.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"LittleBird.png\" type2525b=\"a-u-A-M-H\"/>\n" + 
            "   <icon name=\"LittleBird2.png\" type2525b=\"a-u-A-M-H\"/>\n" + 
            "   <icon name=\"littlebird3.png\" type2525b=\"a-u-A-M-H\"/>\n" + 
            "   <icon name=\"LittleBird4.png\" type2525b=\"a-u-A-M-H\"/>\n" + 
            "   <icon name=\"medical.png\" type2525b=\"a-u-G-U-S-M\"/>\n" + 
            "   <icon name=\"MFF.png\" type2525b=\"a-u-A\"/>\n" + 
            "   <icon name=\"Missle.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"missle2.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"MissleLauncher.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"molotov.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"MP.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"MRAP.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"PC-12.png\" type2525b=\"a-u-A-M-F\"/>\n" + 
            "   <icon name=\"pistol.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"Predator.png\" type2525b=\"a-u-A-M-F-Q\"/>\n" + 
            "   <icon name=\"radar.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"range.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Reaper.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"RECCE.png\" type2525b=\"a-u-A-M-F-R-X\"/>\n" + 
            "   <icon name=\"reticle3.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"revolver.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"rifle.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"rocket.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"RPG.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"Salute.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"seaman.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"shield.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"shield2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"shotgun.png\" type2525b=\"a-u-G-E-W\"/>\n" + 
            "   <icon name=\"SIGINT.png\" type2525b=\"a-u-A-M-F-R-Z\"/>\n" + 
            "   <icon name=\"sniper.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"sniper2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"soldier.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"soldier2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"soldier3.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"soldier4.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"soldier5.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"soldier6.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"submarine.png\" type2525b=\"a-u-U\"/>\n" + 
            "   <icon name=\"Submarine2.png\" type2525b=\"a-u-U\"/>\n" + 
            "   <icon name=\"submarine3.png\" type2525b=\"a-u-U\"/>\n" + 
            "   <icon name=\"surrender.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Tank.png\" type2525b=\"a-u-G-E-V-A-T\"/>\n" + 
            "   <icon name=\"Tank10.png\" type2525b=\"a-u-G-E-V-A-T\"/>\n" + 
            "   <icon name=\"Tank11.png\" type2525b=\"a-u-G-E-V-A-T\"/>\n" + 
            "   <icon name=\"Tank2.png\" type2525b=\"a-u-G-E-V-A-T\"/>\n" + 
            "   <icon name=\"Tank3.png\" type2525b=\"a-u-G-E-V-A-T\"/>\n" + 
            "   <icon name=\"Tank4.png\" type2525b=\"a-u-G-E-V-A-T\"/>\n" + 
            "   <icon name=\"Tank5.png\" type2525b=\"a-u-G-E-V-A-T\"/>\n" + 
            "   <icon name=\"Tank6.png\" type2525b=\"a-u-G-E-V-A-T\"/>\n" + 
            "   <icon name=\"Tank7.png\" type2525b=\"a-u-G-E-V-A-T\"/>\n" + 
            "   <icon name=\"Tank8.png\" type2525b=\"a-u-G-E-V-A-T\"/>\n" + 
            "   <icon name=\"Tank9.png\" type2525b=\"a-u-G-E-V-A-T\"/>\n" + 
            "   <icon name=\"target5.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"team.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"TruckCargo.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"truckcargo2.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"TruckM35.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"UAV_quad.png\" type2525b=\"a-u-A-M-F-Q\"/>\n" + 
            "   <icon name=\"warrior.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Astronaut.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Beggar.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Bicyclist.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"BikeAccident.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"BikeRacer.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"body.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"businessman.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"construction.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"crimescene.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"criminal.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"CrossCountrySki.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"CrossingGuard.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"crosswalk.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"delivery.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"downhillski.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"fall.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"femalecrime.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Fireman.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"freefall.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"FreestyleSkiing.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Handicap.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"ice.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Luge.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Man.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"picket.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Police.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Police2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Protesters.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"restroom.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"riot.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"robber.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"skijump.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"SkiRacing.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"skydive.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"slip.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"SnowShoe.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"suspect.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"thief.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"trash.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"trip.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"walk.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Woman.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Acorn.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Apple.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Banana.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Corn.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Flower.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Flower2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Maple.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Oak.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Orange.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"PalmTree.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"PalmTrees.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Pear.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Pineapple.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"PineTree.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"SunFlower.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Tomato.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Tree.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Tree2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Tree3.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Tree4.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Watermelon.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Wheat.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"BeachChair.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"BeachUmbrella.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Drinks.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Grill.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Lifeguard.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Picnic.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"4x4.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"accident.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Ambulance.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"ATV.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"ATV2.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"baybridge.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Bicycle.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Bike.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"BikeLane.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"biofuel.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Blimp.png\" type2525b=\"a-u-A-C-L\"/>\n" + 
            "   <icon name=\"Blimp2.png\" type2525b=\"a-u-A-C-L\"/>\n" + 
            "   <icon name=\"Boat.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Bridge.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Bridge2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"bridge3.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"bridge4.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Bus.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Bus2.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Bus3.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"BusTicket.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"CableCar.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Car.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Car2.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Car3.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Car4.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Car5.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Car6.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Car7.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Car8.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Car9.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"CargoPort.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"CargoShip.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"CarRack.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Car_Incline.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"caution.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"curves.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Customs.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"DirtBike.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"DoNotEnter.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"DriveThru.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"DumpTruck.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"DumpTruck2.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Exit.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"FarmTractor.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"FireTruck.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"FishingBoat.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Flag.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Flatbed.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Forklift.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Fuel.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"GasPump.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Gondola.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Gondola3.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"GreenLight.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Helicopter.png\" type2525b=\"a-u-A-C-H\"/>\n" + 
            "   <icon name=\"Helicopter2.png\" type2525b=\"a-u-A-C-H\"/>\n" + 
            "   <icon name=\"Helicopter3.png\" type2525b=\"a-u-A-C-H\"/>\n" + 
            "   <icon name=\"Helicopter4.png\" type2525b=\"a-u-A-C-H\"/>\n" + 
            "   <icon name=\"HelicopterPad.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Highway.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"HorseTrailer.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"HotAirBalloon.png\" type2525b=\"a-u-A-C-L\"/>\n" + 
            "   <icon name=\"Humbee.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Incline.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Interstate.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Jeep.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Locomotive.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"LogTruck.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Metro.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Moped.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Motorcycle.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"MountainLift.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"OffRoading.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"OffRoadTruck.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"PickupTruck.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Plane.png\" type2525b=\"a-u-A-C-F\"/>\n" + 
            "   <icon name=\"Plane2.png\" type2525b=\"a-u-A-C-F\"/>\n" + 
            "   <icon name=\"Plane3.png\" type2525b=\"a-u-A-C-F\"/>\n" + 
            "   <icon name=\"Plane4.png\" type2525b=\"a-u-A-C-F\"/>\n" + 
            "   <icon name=\"Plane5.png\" type2525b=\"a-u-A-C-F\"/>\n" + 
            "   <icon name=\"Plane6.png\" type2525b=\"a-u-A-C-F\"/>\n" + 
            "   <icon name=\"Plane7.png\" type2525b=\"a-u-A-C-F\"/>\n" + 
            "   <icon name=\"Plane8.png\" type2525b=\"a-u-A-C-F\"/>\n" + 
            "   <icon name=\"Plane9.png\" type2525b=\"a-u-A-C-F\"/>\n" + 
            "   <icon name=\"PlaneTicket.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"RailCar.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"RailRoad.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"RailRoadCrossing.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"RailTracks.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"RallyPoint.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"RedLight.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Rickshaw.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"RickShaw2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Rocket.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Route.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Sailboat.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Sailboat2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Sailboat3.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"SchoolBus.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"SchoolBus2.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Schooner.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Segway.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Segway2.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Semi.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Semi2.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Ship.png\" type2525b=\"a-u-S\"/>\n" + 
            "   <icon name=\"Ship2.png\" type2525b=\"a-u-S\"/>\n" + 
            "   <icon name=\"Ship3.png\" type2525b=\"a-u-S\"/>\n" + 
            "   <icon name=\"Ship4.png\" type2525b=\"a-u-S\"/>\n" + 
            "   <icon name=\"Sidecar.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Snowmobile.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"SpaceShuttle.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Speed_Train.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"STOP.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Taxi.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Taxi2.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"TourBus.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"TowTruck.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"TractorTrailer.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Trailsign.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Trailsign2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Train.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Train2.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Train3.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Train4.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Train5.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Train6.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"TrainTicket.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Tram.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Trolly.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Truck.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Truck2.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Truck3.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Truck4.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Truck5.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Tunnel.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"TunnelRoad.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"TunnelTrain.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Underground.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Underground2.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Van.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Van2.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Van3.png\" type2525b=\"a-u-G-E-V\"/>\n" + 
            "   <icon name=\"Warning.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Yacht.png\" type2525b=\"a-u-S\"/>\n" + 
            "   <icon name=\"YellowLight.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Icing.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Rain.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Snow.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"Snowflake.png\" type2525b=\"a-u-G\"/>\n" + 
            "   <icon name=\"sun.png\" type2525b=\"a-u-G\"/>\n" + 
            "</iconset>";

    Logger logger = LoggerFactory.getLogger(IconsetIconTest.class);

    private JAXBContext jaxbContext = null;

    private Unmarshaller jaxbUnmarshaller = null;

    @Before
    public void setup() throws Exception {

        // setup JAXB deserializer for Iconset and Icon classes
        ch.qos.logback.classic.Logger root = (ch.qos.logback.classic.Logger) org.slf4j.LoggerFactory.getLogger(ch.qos.logback.classic.Logger.ROOT_LOGGER_NAME);

        // set log level for test to all
        root.setLevel(Level.ALL);

        jaxbContext = JAXBContext.newInstance(Iconset.class, Icon.class);
        jaxbUnmarshaller = jaxbContext.createUnmarshaller();

    }

    @Test
    public void testIconsetDeserialization() throws Exception {

        Iconset iconset = null;

        long start = System.currentTimeMillis();
        iconset = (Iconset) jaxbUnmarshaller.unmarshal(new StringReader(iconsetXml));
        long duration = System.currentTimeMillis() - start;

        logger.debug("iconset deserialization running time: " + duration + " ms");

        logger.debug("number of icons in iconset: " + iconset.getIcons().size() + " deserialized iconset: " + iconset);

        assertNotNull(iconset);
        assertEquals(iconset.getName(), "Default");
        assertEquals(iconset.getUid(), "34ae1613-9645-4222-a9d2-e5f243dea2865");
        assertEquals(iconset.getDefaultFriendly(), "salute.png");
        assertEquals(iconset.getDefaultHostile(), "robber.png");
        assertEquals(iconset.getDefaultUnknown(), "suspect.png");
        assertEquals(iconset.getSkipResize(), true);
        assertEquals(iconset.getVersion(), new Integer(1));
        assertEquals(iconset.getIcons().size(), 820);

        Icon icon = iconset.getIcons().get(0);

        assertNotNull(icon);
        assertEquals(icon.getName(), "antelope.png");
        assertEquals(icon.getType2525b(), "a-u-G");
    }
}
