apiVersion: v1
kind: Service
metadata:
  name: takserver-api
  namespace: takserver
spec:
  type: NodePort
  ports:
    - name: proxied-tcp-8443
      nodePort: 30000
      port: 8443
      targetPort: 8443
      protocol: TCP
    - name: proxied-tcp-8444
      nodePort: 30001
      port: 8444
      targetPort: 8444
      protocol: TCP
    - name: proxied-tcp-8446
      nodePort: 30002
      port: 8446
      targetPort: 8446
      protocol: TCP
  selector:
    app: takserver-api

---
apiVersion: v1
kind: Service
metadata:
  name: takserver-messaging
  namespace: takserver
spec:
  type: NodePort
  ports:
    - name: proxied-tcp-8089
      nodePort: 30003
      port: 8089
      targetPort: 8089
      protocol: TCP
    - name: proxied-tcp-9000
      nodePort: 30004
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: proxied-tcp-9001
      nodePort: 30005
      port: 9001
      targetPort: 9001
      protocol: TCP
    - name: proxied-tcp-8087
      nodePort: 30006
      port: 8087
      targetPort: 8087
      protocol: TCP
    - name: proxied-udp-8087
      nodePort: 30007
      port: 8087
      targetPort: 8087
      protocol: UDP
    - name: proxied-tcp-8088
      nodePort: 30009
      port: 8088
      targetPort: 8088
      protocol: TCP
  selector:
    app: takserver-messaging
