//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.22 at 04:49:56 PM EDT 
//


package com.bbn.marti.citrap.reports;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bbn.marti.citrap.reports package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Reports_QNAME = new QName("", "reports");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bbn.marti.citrap.reports
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReportsType }
     * 
     */
    public ReportsType createReportsType() {
        return new ReportsType();
    }

    /**
     * Create an instance of {@link OptionType }
     * 
     */
    public OptionType createOptionType() {
        return new OptionType();
    }

    /**
     * Create an instance of {@link ReportType }
     * 
     */
    public ReportType createReportType() {
        return new ReportType();
    }

    /**
     * Create an instance of {@link SectionType }
     * 
     */
    public SectionType createSectionType() {
        return new SectionType();
    }

    /**
     * Create an instance of {@link ListType }
     * 
     */
    public ListType createListType() {
        return new ListType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReportsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reports")
    public JAXBElement<ReportsType> createReports(ReportsType value) {
        return new JAXBElement<ReportsType>(_Reports_QNAME, ReportsType.class, null, value);
    }

}
