//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.26 at 09:44:06 AM EDT 
//


package com.bbn.marti.citrap.reports;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for optionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="optionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="title" type="{}stringType" />
 *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="type" type="{}stringType" />
 *       &lt;attribute name="selected" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="value" type="{}stringType" />
 *       &lt;attribute name="constraint" type="{}stringType" />
 *       &lt;attribute name="unitOptions" type="{}stringType" />
 *       &lt;attribute name="unitValue" type="{}stringType" />
 *       &lt;attribute name="spinnerOptions" type="{}stringType" />
 *       &lt;attribute name="spinnerValue" type="{}stringType" />
 *       &lt;attribute name="prompt" type="{}stringType" />
 *       &lt;attribute name="drawMapItem" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="useReportLocation" type="{}stringType" />
 *       &lt;attribute name="id" type="{}stringType" />
 *       &lt;attribute name="source" type="{}stringType" />
 *       &lt;attribute name="destination" type="{}stringType" />
 *       &lt;attribute name="plugin" type="{}stringType" />
 *       &lt;attribute name="uri" type="{}stringType" />
 *       &lt;attribute name="format" type="{}stringType" />
 *       &lt;attribute name="displayType" type="{}stringType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "optionType")
public class OptionType {

    @XmlAttribute(name = "title")
    protected String title;
    @XmlAttribute(name = "required")
    protected Boolean required;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "selected")
    protected Boolean selected;
    @XmlAttribute(name = "value")
    protected String value;
    @XmlAttribute(name = "constraint")
    protected String constraint;
    @XmlAttribute(name = "unitOptions")
    protected String unitOptions;
    @XmlAttribute(name = "unitValue")
    protected String unitValue;
    @XmlAttribute(name = "spinnerOptions")
    protected String spinnerOptions;
    @XmlAttribute(name = "spinnerValue")
    protected String spinnerValue;
    @XmlAttribute(name = "prompt")
    protected String prompt;
    @XmlAttribute(name = "drawMapItem")
    protected Boolean drawMapItem;
    @XmlAttribute(name = "useReportLocation")
    protected String useReportLocation;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "source")
    protected String source;
    @XmlAttribute(name = "destination")
    protected String destination;
    @XmlAttribute(name = "plugin")
    protected String plugin;
    @XmlAttribute(name = "uri")
    protected String uri;
    @XmlAttribute(name = "format")
    protected String format;
    @XmlAttribute(name = "displayType")
    protected String displayType;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the required property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequired(Boolean value) {
        this.required = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the selected property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSelected() {
        return selected;
    }

    /**
     * Sets the value of the selected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSelected(Boolean value) {
        this.selected = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the constraint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConstraint() {
        return constraint;
    }

    /**
     * Sets the value of the constraint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConstraint(String value) {
        this.constraint = value;
    }

    /**
     * Gets the value of the unitOptions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOptions() {
        return unitOptions;
    }

    /**
     * Sets the value of the unitOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitOptions(String value) {
        this.unitOptions = value;
    }

    /**
     * Gets the value of the unitValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitValue() {
        return unitValue;
    }

    /**
     * Sets the value of the unitValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitValue(String value) {
        this.unitValue = value;
    }

    /**
     * Gets the value of the spinnerOptions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpinnerOptions() {
        return spinnerOptions;
    }

    /**
     * Sets the value of the spinnerOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpinnerOptions(String value) {
        this.spinnerOptions = value;
    }

    /**
     * Gets the value of the spinnerValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpinnerValue() {
        return spinnerValue;
    }

    /**
     * Sets the value of the spinnerValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpinnerValue(String value) {
        this.spinnerValue = value;
    }

    /**
     * Gets the value of the prompt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrompt() {
        return prompt;
    }

    /**
     * Sets the value of the prompt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrompt(String value) {
        this.prompt = value;
    }

    /**
     * Gets the value of the drawMapItem property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDrawMapItem() {
        return drawMapItem;
    }

    /**
     * Sets the value of the drawMapItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDrawMapItem(Boolean value) {
        this.drawMapItem = value;
    }

    /**
     * Gets the value of the useReportLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseReportLocation() {
        return useReportLocation;
    }

    /**
     * Sets the value of the useReportLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseReportLocation(String value) {
        this.useReportLocation = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the plugin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlugin() {
        return plugin;
    }

    /**
     * Sets the value of the plugin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlugin(String value) {
        this.plugin = value;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the displayType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayType() {
        return displayType;
    }

    /**
     * Sets the value of the displayType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayType(String value) {
        this.displayType = value;
    }

}
