//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.26 at 09:44:06 AM EDT 
//


package com.bbn.marti.citrap.reports;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for reportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reportType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="section" type="{}sectionType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{}stringType" />
 *       &lt;attribute name="title" type="{}stringType" />
 *       &lt;attribute name="userCallsign" type="{}stringType" />
 *       &lt;attribute name="userDescription" type="{}stringType" />
 *       &lt;attribute name="dateTime" type="{}stringType" />
 *       &lt;attribute name="dateTimeDescription" type="{}stringType" />
 *       &lt;attribute name="location" type="{}stringType" />
 *       &lt;attribute name="locationDescription" type="{}stringType" />
 *       &lt;attribute name="tags" type="{}stringType" />
 *       &lt;attribute name="eventScale" type="{}stringType" />
 *       &lt;attribute name="scaleDescription" type="{}stringType" />
 *       &lt;attribute name="importance" type="{}stringType" />
 *       &lt;attribute name="status" type="{}stringType" />
 *       &lt;attribute name="id" type="{}stringType" />
 *       &lt;attribute name="warning" type="{}stringType" />
 *       &lt;attribute name="tak" type="{}stringType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "report")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reportType", propOrder = {
    "section"
})
public class ReportType {

    @XmlElement(required = true)
    protected List<SectionType> section;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "title")
    protected String title;
    @XmlAttribute(name = "userCallsign")
    protected String userCallsign;
    @XmlAttribute(name = "userDescription")
    protected String userDescription;
    @XmlAttribute(name = "dateTime")
    protected String dateTime;
    @XmlAttribute(name = "dateTimeDescription")
    protected String dateTimeDescription;
    @XmlAttribute(name = "location")
    protected String location;
    @XmlAttribute(name = "locationDescription")
    protected String locationDescription;
    @XmlAttribute(name = "tags")
    protected String tags;
    @XmlAttribute(name = "eventScale")
    protected String eventScale;
    @XmlAttribute(name = "scaleDescription")
    protected String scaleDescription;
    @XmlAttribute(name = "importance")
    protected String importance;
    @XmlAttribute(name = "status")
    protected String status;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "warning")
    protected String warning;
    @XmlAttribute(name = "tak")
    protected String tak;

    /**
     * Gets the value of the section property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the section property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SectionType }
     * 
     * 
     */
    public List<SectionType> getSection() {
        if (section == null) {
            section = new ArrayList<SectionType>();
        }
        return this.section;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the userCallsign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserCallsign() {
        return userCallsign;
    }

    /**
     * Sets the value of the userCallsign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserCallsign(String value) {
        this.userCallsign = value;
    }

    /**
     * Gets the value of the userDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDescription() {
        return userDescription;
    }

    /**
     * Sets the value of the userDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDescription(String value) {
        this.userDescription = value;
    }

    /**
     * Gets the value of the dateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateTime(String value) {
        this.dateTime = value;
    }

    /**
     * Gets the value of the dateTimeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateTimeDescription() {
        return dateTimeDescription;
    }

    /**
     * Sets the value of the dateTimeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateTimeDescription(String value) {
        this.dateTimeDescription = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the locationDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationDescription() {
        return locationDescription;
    }

    /**
     * Sets the value of the locationDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationDescription(String value) {
        this.locationDescription = value;
    }

    /**
     * Gets the value of the tags property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTags(String value) {
        this.tags = value;
    }

    /**
     * Gets the value of the eventScale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventScale() {
        return eventScale;
    }

    /**
     * Sets the value of the eventScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventScale(String value) {
        this.eventScale = value;
    }

    /**
     * Gets the value of the scaleDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScaleDescription() {
        return scaleDescription;
    }

    /**
     * Sets the value of the scaleDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScaleDescription(String value) {
        this.scaleDescription = value;
    }

    /**
     * Gets the value of the importance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportance() {
        return importance;
    }

    /**
     * Sets the value of the importance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportance(String value) {
        this.importance = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the warning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarning() {
        return warning;
    }

    /**
     * Sets the value of the warning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarning(String value) {
        this.warning = value;
    }

    /**
     * Gets the value of the tak property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTak() {
        return tak;
    }

    /**
     * Sets the value of the tak property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTak(String value) {
        this.tak = value;
    }

}
