//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.26 at 09:44:06 AM EDT
//


package com.bbn.marti.citrap.reports;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sectionType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * {@code
 * &lt;complexType name="sectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="option" type="{}optionType"/>
 *         &lt;element name="list" type="{}listType"/>
 *         &lt;element name="section" type="{}sectionType"/>
 *       &lt;/choice>
 *       &lt;attribute name="title" type="{}stringType" />
 *       &lt;attribute name="role" type="{}stringType" />
 *       &lt;attribute name="invert" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="type" type="{}stringType" />
 *       &lt;attribute name="selected" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="id" type="{}stringType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * }
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sectionType", propOrder = {
    "optionOrListOrSection"
})
public class SectionType {

    @XmlElements({
        @XmlElement(name = "option", type = OptionType.class),
        @XmlElement(name = "list", type = ListType.class),
        @XmlElement(name = "section", type = SectionType.class)
    })
    protected List<Object> optionOrListOrSection;
    @XmlAttribute(name = "title")
    protected String title;
    @XmlAttribute(name = "role")
    protected String role;
    @XmlAttribute(name = "invert")
    protected Boolean invert;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "selected")
    protected Boolean selected;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the optionOrListOrSection property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the optionOrListOrSection property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOptionOrListOrSection().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OptionType }
     * {@link ListType }
     * {@link SectionType }
     *
     *
     */
    public List<Object> getOptionOrListOrSection() {
        if (optionOrListOrSection == null) {
            optionOrListOrSection = new ArrayList<Object>();
        }
        return this.optionOrListOrSection;
    }

    /**
     * Gets the value of the title property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the role property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the invert property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isInvert() {
        return invert;
    }

    /**
     * Sets the value of the invert property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setInvert(Boolean value) {
        this.invert = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the selected property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isSelected() {
        return selected;
    }

    /**
     * Sets the value of the selected property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setSelected(Boolean value) {
        this.selected = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

}
