# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takmessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protobuf_msg.cotevent_pb2 as cotevent__pb2
import protobuf_msg.takcontrol_pb2 as takcontrol__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='takmessage.proto',
  package='atakmap.commoncommo.protobuf.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10takmessage.proto\x12\x1f\x61takmap.commoncommo.protobuf.v1\x1a\x0e\x63otevent.proto\x1a\x10takcontrol.proto\"\x8a\x01\n\nTakMessage\x12?\n\ntakControl\x18\x01 \x01(\x0b\x32+.atakmap.commoncommo.protobuf.v1.TakControl\x12;\n\x08\x63otEvent\x18\x02 \x01(\x0b\x32).atakmap.commoncommo.protobuf.v1.CotEventb\x06proto3'
  ,
  dependencies=[cotevent__pb2.DESCRIPTOR,takcontrol__pb2.DESCRIPTOR,])




_TAKMESSAGE = _descriptor.Descriptor(
  name='TakMessage',
  full_name='atakmap.commoncommo.protobuf.v1.TakMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='takControl', full_name='atakmap.commoncommo.protobuf.v1.TakMessage.takControl', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cotEvent', full_name='atakmap.commoncommo.protobuf.v1.TakMessage.cotEvent', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=226,
)

_TAKMESSAGE.fields_by_name['takControl'].message_type = takcontrol__pb2._TAKCONTROL
_TAKMESSAGE.fields_by_name['cotEvent'].message_type = cotevent__pb2._COTEVENT
DESCRIPTOR.message_types_by_name['TakMessage'] = _TAKMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TakMessage = _reflection.GeneratedProtocolMessageType('TakMessage', (_message.Message,), {
  'DESCRIPTOR' : _TAKMESSAGE,
  '__module__' : 'takmessage_pb2'
  # @@protoc_insertion_point(class_scope:atakmap.commoncommo.protobuf.v1.TakMessage)
  })
_sym_db.RegisterMessage(TakMessage)


# @@protoc_insertion_point(module_scope)
