# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: track.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='track.proto',
  package='atakmap.commoncommo.protobuf.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0btrack.proto\x12\x1f\x61takmap.commoncommo.protobuf.v1\"&\n\x05Track\x12\r\n\x05speed\x18\x01 \x01(\x01\x12\x0e\n\x06\x63ourse\x18\x02 \x01(\x01\x62\x06proto3'
)




_TRACK = _descriptor.Descriptor(
  name='Track',
  full_name='atakmap.commoncommo.protobuf.v1.Track',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='atakmap.commoncommo.protobuf.v1.Track.speed', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='course', full_name='atakmap.commoncommo.protobuf.v1.Track.course', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['Track'] = _TRACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Track = _reflection.GeneratedProtocolMessageType('Track', (_message.Message,), {
  'DESCRIPTOR' : _TRACK,
  '__module__' : 'track_pb2'
  # @@protoc_insertion_point(class_scope:atakmap.commoncommo.protobuf.v1.Track)
  })
_sym_db.RegisterMessage(Track)


# @@protoc_insertion_point(module_scope)
